# Generated by Django 5.2.6 on 2026-08-31 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MBTApp', '0014_salesrepresentative_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitephotos',
            name='general_contracting_1',
            field=models.CharField(blank=True, default='https://pub-055b6d77c1e84acda77dbc29041f73ff.r2.dev/media/uploads/0b5b6f5c26b1.webp', max_length=500, verbose_name='Generalne Wykonawstwo — magazyny'),
        ),
        migrations.AddField(
            model_name='sitephotos',
            name='general_contracting_2',
            field=models.CharField(blank=True, default='https://pub-055b6d77c1e84acda77dbc29041f73ff.r2.dev/media/uploads/ed67bb1b2b03.webp', max_length=500, verbose_name='Generalne Wykonawstwo — self storage'),
        ),
        migrations.AddField(
            model_name='sitephotos',
            name='hale_magazynowe_1',
            field=models.CharField(blank=True, default='https://pub-055b6d77c1e84acda77dbc29041f73ff.r2.dev/media/uploads/bdabf42fbc92.jpg', max_length=500, verbose_name='Hale Magaz. — zdjęcie 1'),
        ),
        migrations.AddField(
            model_name='sitephotos',
            name='hale_magazynowe_hero',
            field=models.CharField(blank=True, default='https://pub-055b6d77c1e84acda77dbc29041f73ff.r2.dev/media/uploads/0b5b6f5c26b1.webp', max_length=500, verbose_name='Hale Magaz. — hero'),
        ),
        migrations.AddField(
            model_name='sitephotos',
            name='hale_przemyslowe_1',
            field=models.CharField(blank=True, default='https://pub-055b6d77c1e84acda77dbc29041f73ff.r2.dev/media/uploads/261907cbff38.jpg', max_length=500, verbose_name='Hale Przem. — zdjęcie 1'),
        ),
        migrations.AddField(
            model_name='sitephotos',
            name='hale_przemyslowe_2',
            field=models.CharField(blank=True, default='https://pub-055b6d77c1e84acda77dbc29041f73ff.r2.dev/media/uploads/bdabf42fbc92.jpg', max_length=500, verbose_name='Hale Przem. — zdjęcie 2 (ESG)'),
        ),
        migrations.AddField(
            model_name='sitephotos',
            name='hale_przemyslowe_hero',
            field=models.CharField(blank=True, default='https://pub-055b6d77c1e84acda77dbc29041f73ff.r2.dev/media/uploads/29cd5ab28014.jpg', max_length=500, verbose_name='Hale Przem. — hero'),
        ),
        migrations.AddField(
            model_name='sitephotos',
            name='obiekty_komercyjne_1',
            field=models.CharField(blank=True, default='https://pub-055b6d77c1e84acda77dbc29041f73ff.r2.dev/media/uploads/261907cbff38.jpg', max_length=500, verbose_name='Obiekty Komercyjne — zdjęcie 1'),
        ),
        migrations.AddField(
            model_name='sitephotos',
            name='obiekty_komercyjne_2',
            field=models.CharField(blank=True, default='https://pub-055b6d77c1e84acda77dbc29041f73ff.r2.dev/media/uploads/ed67bb1b2b03.webp', max_length=500, verbose_name='Obiekty Komercyjne — zdjęcie 2 (wnętrza)'),
        ),
        migrations.AddField(
            model_name='sitephotos',
            name='obiekty_komercyjne_hero',
            field=models.CharField(blank=True, default='https://pub-055b6d77c1e84acda77dbc29041f73ff.r2.dev/media/uploads/bdabf42fbc92.jpg', max_length=500, verbose_name='Obiekty Komercyjne — hero'),
        ),
    ]
