# Generated by Django 5.2.6 on 2026-08-31 16:46

import MBTApp.models
from django.db import migrations, models

def copy_work_photos(apps, schema_editor):
    SitePhotos = apps.get_model('MBTApp', 'SitePhotos')
    for sp in SitePhotos.objects.all():
        gallery = []
        # Add them in the order they were displayed in the template: 4, 5, 6, 7, 8, 1, 2, 3
        # If they are empty, we just ignore them or add them anyway
        for i in [4, 5, 6, 7, 8, 1, 2, 3]:
            val = getattr(sp, f'work_{i}')
            if val:
                gallery.append(val)
        sp.work_gallery = gallery
        sp.save()

class Migration(migrations.Migration):

    dependencies = [
        ('MBTApp', '0015_sitephotos_general_contracting_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitephotos',
            name='work_gallery',
            field=models.JSONField(blank=True, default=MBTApp.models.default_work_gallery, verbose_name='Galeria pracy'),
        ),
        migrations.RunPython(copy_work_photos, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='sitephotos',
            name='work_1',
        ),
        migrations.RemoveField(
            model_name='sitephotos',
            name='work_2',
        ),
        migrations.RemoveField(
            model_name='sitephotos',
            name='work_3',
        ),
        migrations.RemoveField(
            model_name='sitephotos',
            name='work_4',
        ),
        migrations.RemoveField(
            model_name='sitephotos',
            name='work_5',
        ),
        migrations.RemoveField(
            model_name='sitephotos',
            name='work_6',
        ),
        migrations.RemoveField(
            model_name='sitephotos',
            name='work_7',
        ),
        migrations.RemoveField(
            model_name='sitephotos',
            name='work_8',
        ),
    ]
