# Generated by Django 5.2.6 on 2026-08-31 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MBTApp', '0016_remove_sitephotos_work_1_remove_sitephotos_work_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='office_site_gallery',
            field=models.JSONField(blank=True, default=list, verbose_name='Galeria placu budowy (lista URL-i)'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='office_site_photo',
            field=models.CharField(blank=True, default='/static/img/mbt/DSC03738-scaled-c238f3f3.jpeg', max_length=500, verbose_name='Zdjęcie placu budowy (URL) - stare'),
        ),
    ]
