# Generated by Django 5.2.6 on 2026-08-31 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MBTApp', '0019_alter_bannertemplate_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannertemplate',
            name='size',
            field=models.CharField(choices=[('200x100', '2 m × 1 m (banner standard)'), ('250x100', '2,5 m × 1 m'), ('300x100', '3 m × 1 m'), ('400x100', '4 m × 1 m'), ('400x200', '4 m × 2 m'), ('250x150_bhp', 'Baner BHP (2,5 m × 1,5 m)'), ('bioz', 'Tablica BIOZ'), ('informacyjna', 'Tablica informacyjna'), ('200x100_apology', 'Baner „Przepraszamy za utrudnienia" (2 m × 1 m)'), ('300x100_apology', 'Baner „Przepraszamy za utrudnienia" (3 m × 1 m)'), ('600x200_billboard', 'Billboard (6 m × 2 m)'), ('znak_wjazd_logo', 'Znak: Wjazd na budowę (z logiem)'), ('znak_wjazd_bez', 'Znak: Wjazd na budowę (bez loga)'), ('znak_biuro_logo', 'Znak: Biuro budowy (z logiem)'), ('znak_biuro_bez', 'Znak: Biuro budowy (bez loga)'), ('znak_kierunek_prawo', 'Znak kierunkowy: Prawo'), ('znak_kierunek_lewo', 'Znak kierunkowy: Lewo'), ('znak_kierunek_prosto', 'Znak kierunkowy: Prosto / Bez strzałek')], max_length=20, verbose_name='Rozmiar'),
        ),
    ]
