# Generated by Django 5.2.6 on 2026-09-01 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MBTApp', '0020_alter_bannertemplate_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nazwa')),
                ('image', models.FileField(upload_to='awards/', verbose_name='Logotyp / Grafika')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Kolejność')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktywne')),
            ],
            options={
                'verbose_name': 'Wyróżnienie / Partnerstwo',
                'verbose_name_plural': 'Wyróżnienia i Partnerstwa',
                'ordering': ['order', 'name'],
            },
        ),
    ]
