# Generated by Django 5.2.6 on 2026-09-01 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MBTApp', '0021_award'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='hero_subtitle',
            field=models.CharField(default='Z pasją budujemy Wasze biznesy', max_length=200, verbose_name='Podtytuł hero'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='hero_text',
            field=models.TextField(default='Jeden team – pełna realizacja. <strong>Od projektu aż po dach!</strong> Budujemy hale magazynowe, produkcyjne i usługowe pod klucz.', verbose_name='Tekst hero'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='hero_title1',
            field=models.CharField(default='Twój Generalny', max_length=200, verbose_name='Tytuł hero 1'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='hero_title2',
            field=models.CharField(default='Wykonawca', max_length=200, verbose_name='Tytuł hero 2'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='t_hero_subtitle',
            field=models.JSONField(blank=True, default=dict, verbose_name='Podtytuł hero — tłum.'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='t_hero_text',
            field=models.JSONField(blank=True, default=dict, verbose_name='Tekst hero — tłum.'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='t_hero_title1',
            field=models.JSONField(blank=True, default=dict, verbose_name='Tytuł hero 1 — tłum.'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='t_hero_title2',
            field=models.JSONField(blank=True, default=dict, verbose_name='Tytuł hero 2 — tłum.'),
        ),
    ]
