# Generated by Django 5.1 on 2026-09-09 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MBTApp', '0022_siteconfig_hero_subtitle_siteconfig_hero_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='gallery',
            field=models.JSONField(blank=True, default=list, verbose_name='Galeria (lista URL-i)'),
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.CharField(blank=True, max_length=500, verbose_name='Zdjęcie główne (URL)'),
        ),
        migrations.AlterField(
            model_name='award',
            name='image',
            field=models.CharField(blank=True, max_length=500, verbose_name='Logotyp (URL)'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='phone_href',
            field=models.CharField(default='+48881444333', max_length=40, verbose_name='Telefon (href)'),
        ),
    ]
