# Generated by Django 5.1 on 2026-09-09 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MBTApp', '0023_article_gallery_alter_article_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Nazwa sektora (PL)')),
                ('slug', models.CharField(blank=True, help_text='np. konstrukcje-stalowe', max_length=200, verbose_name='Slug (dla URL)')),
                ('view_name', models.CharField(default='sectorDetail', help_text='np. sectorDetail, halePrzemyslowe', max_length=100, verbose_name='Nazwa widoku')),
                ('opis', models.TextField(verbose_name='Opis (PL)')),
                ('icon', models.CharField(default='ri-building-2-line', max_length=100, verbose_name='Ikona (klasa RemixIcon)')),
                ('image', models.CharField(blank=True, max_length=500, verbose_name='Zdjęcie (URL)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Kolejność')),
                ('t_title', models.JSONField(blank=True, default=dict, verbose_name='Nazwa — tłumaczenia')),
                ('t_opis', models.JSONField(blank=True, default=dict, verbose_name='Opis — tłumaczenia')),
            ],
            options={
                'verbose_name': 'Sektor B2B',
                'verbose_name_plural': 'Sektory B2B (Nasze Specjalizacje)',
                'ordering': ['order'],
            },
        ),
    ]
