# Generated by Django 5.1 on 2026-09-14 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MBTApp', '0024_sector'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='social_instagram',
            field=models.URLField(blank=True, verbose_name='Instagram'),
        ),
    ]
